### ISSUE TITLE
Siri times out when opening/closing garage door

### ISSUE THREAD

**Issue by redec** [KraigM/homebridge-wink#23] opened 2016-01-18 22:27 UTC
When I tell Siri to open/close my garage door, it all works good but she gives up waiting for a response before the door actually finishes opening/closing.  Is it possible to tweak that timeout setting?

**Comment by KraigM** [comment] 2016-01-23 16:44
Duplicate of #14

**Comment by KraigM** [comment] 2016-01-23 16:44
Released with version 1.1.0

**Closed by KraigM** 2016-01-23 16:44 UTC
Labels: duplicate
