### ISSUE TITLE
Pivot Power Genius communication issues

### ISSUE THREAD

**Issue by rbharris1** [KraigM/homebridge-wink#26] opened 2016-01-20 14:18 UTC
Note: I left a previous version of this comment on the closed enhancement request a few days ago, but wasn't sure if it would be seen since the issue was closed, so here's an updated version after more testing....

I installed 1.0.3 and...viola...homebridge sees my pivot power genius (ppg) outlets!

The PPG devices also appear in the Insteon+ app, but they don't have any controls. When I click on them they just show the name of the device with the placeholders for mfr and serial no. When I try to operate by Siri, response is "Sorry, I can't do that."

To test the problem, I removed Insteon+ and installed iDevices. With iDevices, the PPG outlets show up as switchable devices. When I toggle the on/off switch in the app, the homebridge server output shows, for instance, "Changing target property 'powered' of the undefined called Ava's Radiator to 0" (or 1, depending on the device state known to the app). This change does not get pushed to the PPG outlet. When I leave the app and return or when I refresh the devices in the app, the powered status of the PPG outlets in the app is changed back to whatever the powered status was when the app was installed. When I try toggling a PPG device in Siri, I get the same response as with Insteon+, "Sorry, I can't do that."

Finally, I tried the Elegato Eve app. It has the same behavior as iDevices. However, when I try to toggle a PPG outlet, a little red warning symbol appears with the message, "HomeKit reported a communication failure. Please try again."

I should add that with all three apps, the following devices work flawlessly: Chamberlain myQ, GE Link bulbs, and Cree connected bulbs.

Thanks for all your work on this plugin! Any guidance you could provide would be appreciated.

**Comment by KraigM** [comment] 2016-01-23 16:43
Duplicate of #14

**Comment by KraigM** [comment] 2016-01-23 16:44
Released with version 1.1.0

**Closed by KraigM** 2016-01-23 16:44 UTC
Labels: duplicate
